[[services]]
name = "web"
dockerfilePath = "Dockerfile"

[services.deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "api"
dockerfilePath = "server/Dockerfile.api"
buildContext = "server"

[services.deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
